eureka:
  instance:
    instance-id: eureka:${random.value}
  server:
    eviction-interval-timer-in-ms: 2000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
    peer-node-read-timeout-ms: 500
  client:
    #false表示向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
spring:
  security:
    user:
      name: root
      password: root
project:
  info: dev