server:
  port: 9527

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://root:root@eureka1:7001/eureka,http://root:root@eureka2:7002/eureka
  instance:
    instance-id: gateway:${random.value}
    prefer-ip-address: true     #访问路径可以显示IP地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: gateway
  zipkin:
    base-url: http://192.168.56.102:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
  cloud:
    gateway:
      routes:
      - id: consumer_routh   #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://consumer-order         #匹配后提供服务的路由地址
        predicates:
        - Path=/feign/**         # 断言，路径相匹配的进行路由
      - id: provider_routh   #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: lb://provider-payment         #匹配后提供服务的路由地址
        predicates:
        - Path=/payment/**         # 断言，路径相匹配的进行路由
project:
  info: dev