spring:
  application:
    name: provider-payment
  zipkin:
    base-url: http://192.168.56.102:9411
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.56.102
                port: 5672
                username: root
                password: root
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: payExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: payment-group #配置分组，分摊消息，且一旦服务down机，不分摊的消息也会持久化，服务器启动后会自动获取这部分消息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/cloud21-learn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  #rabbitmq相关配置 15672是Web管理界面的端口；5672是MQ访问的端口
#  rabbitmq:
#    host: 192.168.56.102
#    port: 5672
#    username: root
#    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hjrpc.api.entity    # 所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://root:root@eureka1:7001/eureka,http://root:root@eureka2:7002/eureka
  instance:
    prefer-ip-address: true     #访问路径可以显示IP地址
    instance-id: provider-payment:${random.value}
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2
management:
  endpoints:
    web:
      exposure:
        include: '*'
project:
  info: dev
